[package]
name = "gprepo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3"
git2 = "0.13.24"
globset = "0.4.8"
structopt = "0.3.25"
walkdir = "2"
